### ISSUE TITLE
Force lowercase for .small class

### ISSUE THREAD

**Issue by ashenden** [mesosphere/cnvs#45]

**Comment by jfurrow** [comment]
I don't think this is the right solution. Let's add some class for `label` and `.label` that just unsets the `text-transform` property.

**Comment by mlunoe** [comment]
I agree with @jfurrow here

**Comment by jfurrow** [comment]
@ashenden Just to recap our in-person convo, let's instead create a `.text-no-transform` (or whatever) which just turns off the text-transform for any element.
