### ISSUE TITLE
.form-control-select select doesn't fill its parent

### ISSUE THREAD

**Issue by jfurrow** [mesosphere/cnvs#48]
In the following screenshot, the `select` element is highlighted. Note how it doesn't fill its container. This means nothing happens when the user clicks on the down arrow.

![](https://cl.ly/241P0M1V2k0O/Screen%20Shot%202016-11-16%20at%201.39.56%20PM.png)

**Comment by ashenden** [comment]
Fixed with PR https://github.com/mesosphere/canvas/pull/55
