### ISSUE TITLE
Radio buttons are not perfect ciricles

### ISSUE THREAD

**Issue by jfurrow** [mesosphere/cnvs#50]
Now that we're using the CNVS radio buttons, I'm noticing they're not circles.

![](https://cl.ly/3d43093u2A2l/Screen%20Shot%202016-11-18%20at%2010.05.20%20AM.png)

**Comment by ashenden** [comment]
Any idea how to fix this one?  I'm using `rem` for the size, which is resulting in a longer shape.

**Comment by jfurrow** [comment]
It happens when the calculated pixel value is not a whole number, so I'd suggest using `px` units instead of `rem` for these bad boys.
