### ISSUE TITLE
Disabled selects aren't styled

### ISSUE THREAD

**Issue by jfurrow** [mesosphere/cnvs#51]
Right now it's impossible to tell if a select field is disabled.

**Comment by ashenden** [comment]
@jfurrow are you sure this is an issue?  By adding class `.disabled` to the element `.form-control .form-control-select`, the form-control-select is styled to appear disabled, just like other form-control elements.  You will also need to disable the nested `select` as well.

https://cl.ly/0y3L3w0o2N1p

**Comment by jfurrow** [comment]
Ah that makes sense, I was just using the `disabled` prop on the select element itself.
