### ISSUE TITLE
Dropdown arrows are broken in firefox

### ISSUE THREAD

**Issue by jfurrow** [mesosphere/cnvs#72]
Firefox doesn't seem to count the pseudo-elements as a valid flex element. For the time being I've removed `display: inline-flex` from dropdown buttons in DC/OS UI.

![](https://cl.ly/191C0L2Q0S3q/Screen%20Shot%202016-12-13%20at%201.59.55%20PM.png)

**Comment by jfurrow** [comment]
Ping @ashenden (I'm not sure if you're getting alerts about issues automatically)

**Comment by ashenden** [comment]
Hmm.  ok.  Weird.

**Comment by jfurrow** [comment]
Codepen for fun: http://codepen.io/yeahjohnnn/pen/ObBOBG
