### ISSUE TITLE
Values of disabled input fields are illegible

### ISSUE THREAD

**Issue by jfurrow** [mesosphere/cnvs#76]
In DC/OS UI, we're displaying this modal with a disabled input field because the user cannot edit it after creating it, but should still be able to see that it has a `value`.

![](https://cl.ly/3W1r151v1I2c/Screen%20Shot%202016-12-16%20at%2011.23.11%20AM.png)

**Comment by ashenden** [comment]
@jfurrow I'm not sure when this screenshot was taken, but we already updated the values for `disabled` controls back in Dec https://github.com/mesosphere/cnvs/pull/80.

**Comment by jfurrow** [comment]
@ashenden This is still a problem in the most recent release of CNVS (1.1.6) — perhaps we need to do another release?

**Comment by ashenden** [comment]
@jfurrow are you sure?  Looking at the commit history (https://cl.ly/0f2j3n3E0G3q) the update to `.form-control` disabled vars made it's way into `1.1.6`.  Are we using `1.1.6` in DC/OS?

By "Still a problem" do you mean, that the fix hasn't made it's way in, or are you saying that despite the fix, this is still a problem?

**Comment by jfurrow** [comment]
I mean that the fix is not in the version 1.1.6 that is published on NPM. When I run CNVS locally I can see the fix.
